env:
  - GO111MODULE=on
before:
  hooks:
  - go mod download
  - go build -o bin/beehive-web ./cmd/web
  - go build -o bin/beehive-tray ./cmd/tray
builds:
  -
    binary: beehive
    ldflags: -s -w -X main.Version={{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
    flags:
      - -tags=embed
    hooks:
      pre: go-bindata --tags embed --pkg api -o api/bindata.go --ignore config/.git assets/... config/...
signs:
  - artifacts: checksum
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  -
    id: default
    package_name: beehive-tray
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: com.github.muesli.beehive
    homepage: https://github.com/muesli/beehive
    maintainer: Beehive Developers
    description: Beehive's notification area application
    license: GNU AFFERO GENERAL PUBLIC LICENSE (AGPL-3)
    formats:
      - deb
    dependencies:
      - libwebkit2gtk-4.0-37
    bindir: /usr/bin
    epoch: 1
    files:
      "bin/beehive-web": "/usr/bin/beehive-web"
      "bin/beehive-tray": "/usr/bin/beehive-tray"
      "assets/logo.png": "/usr/share/pixmaps/beehive-tray.png"
      "assets/beehive-tray.desktop": "/usr/share/applications/beehive-tray.desktop"