#!/bin/bash
set -e

cleanup_linux() {
  true
}

trap cleanup_linux EXIT

nativefier -e $ELECTRON_VERSION --icon $BASE_PATH/assets/logo.png --name Beehive http://localhost:8181 build/app

mkdir -p build/app
cp beehive build/app
chmod +x build/app/beehive
cat > build/app/beehive-linux-x64/beehive.wrapper << "EOF"
#!/bin/bash

export BASE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/../" && pwd )"

# Start the daemon
$BASE_PATH/beehive --config $SNAP_USER_DATA/beehive.conf &
bpid=$!
finish() {
  [[ -z "$bpid" ]] || kill $bpid > /dev/null 2>&1
}
trap finish EXIT

# Start the GUI shell
$BASE_PATH/beehive-linux-x64/beehive
EOF
chmod +x build/app/beehive-linux-x64/beehive.wrapper
snapcraft
