#!/bin/bash
set -e

tmpd=$TMPDIR/beehive.iconset
icns=$TMPDIR/beehive.icns
logfile=$TMPDIR/build-icns.log

cleanup() {
  rm -rf $tmpd
  rm -f $logfile
}

trap cleanup EXIT

{
  mkdir $tmpd
  sips -z 16 16    assets/logo.png --out $tmpd/icon_16x16.png
  sips -z 32 32    assets/logo.png --out $tmpd/icon_16x16@2x.png
  sips -z 32 32    assets/logo.png --out $tmpd/icon_32x32.png
  sips -z 64 64    assets/logo.png --out $tmpd/icon_32x32@2x.png
  sips -z 128 128  assets/logo.png --out $tmpd/icon_128x128.png
  sips -z 256 256  assets/logo.png --out $tmpd/icon_128x128@2x.png
  sips -z 256 256  assets/logo.png --out $tmpd/icon_256x256.png
  sips -z 512 512  assets/logo.png --out $tmpd/icon_256x256@2x.png
  sips -z 512 512  assets/logo.png --out $tmpd/icon_512x512.png
  cp assets/logo.png $tmpd/icon_512x512@2x.png
  iconutil -c icns $tmpd
} > $logfile 2>&1

echo $icns
